version: '3.7'

volumes:
  caddy-volume:

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    ports:
      - '10000:10000'
      - '10001:10001'
    volumes:
      - ./server/v2_config.json:/etc/v2ray/config.json

  caddy:
    image: caddy
    container_name: caddy
    restart: always
    depends_on: 
      - "v2ray"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./server/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/site
      - ./server/caddy_data:/data
      - caddy-volume:/config
