version: '3.7'

volumes:
  caddy-volume:

services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/site
      - ./docker_data:/docker_data

  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    ports:
      - '10000:10000'
      - '10001:10001'
    volumes:
      - ./config.json:/etc/v2ray/config.json
